CREATE DATABASE QLGV
USE QLGV

-- TUAN 1

CREATE TABLE LOP
(
MALOP CHAR(3) PRIMARY KEY,
TENLOP VARCHAR(40),
SISO TINYINT,
MAGVCN CHAR(4),
TRGLOP CHAR(5) FOREIGN KEY REFERENCES HOCVIEN(MAHV)
)
CREATE TABLE MONHOC
(
MAMH VARCHAR(10) PRIMARY KEY,
TENMH VARCHAR(40),
TCLT TINYINT,
TCTH TINYINT,
MAKHOA VARCHAR(4) FOREIGN KEY REFERENCES KHOA(MAKHOA)
)
CREATE TABLE HOCVIEN
(
MAHV CHAR(5) PRIMARY KEY,
HO VARCHAR(40),
TEN VARCHAR(10),
NGSINH SMALLDATETIME,
GIOITINH VARCHAR(3),
NOISINH VARCHAR(40),
MALOP CHAR(3)
)
CREATE TABLE KHOA
(
MAKHOA VARCHAR(4) PRIMARY KEY,
TENKHOA VARCHAR(40),
NGTLAP SMALLDATETIME,
TRGKHOA CHAR(4) FOREIGN KEY REFERENCES GIAOVIEN(MAGV)
)
CREATE TABLE DIEUKIEN
(
MAMH VARCHAR(10) FOREIGN KEY REFERENCES MONHOC(MAMH),
MAMH_TRUOC VARCHAR(10),
CONSTRAINT DK_MH PRIMARY KEY(MAMH,MAMH_TRUOC)
)
CREATE TABLE GIAOVIEN
(
MAGV CHAR(4) PRIMARY KEY,
HOTEN VARCHAR(40),
HOCVI VARCHAR(10),
HOCHAM VARCHAR(10),
GIOITINH VARCHAR(3),
NGSINH SMALLDATETIME,
NGVL SMALLDATETIME,
HESO NUMERIC(4,2),
MUCLUONG MONEY,
MAKHOA VARCHAR(4)
)
CREATE TABLE GIANGDAY
(
MALOP CHAR(3) FOREIGN KEY REFERENCES LOP(MALOP),
MAMH VARCHAR(10) FOREIGN KEY REFERENCES MONHOC(MAMH),
MAGV CHAR(4) FOREIGN KEY REFERENCES GIAOVIEN(MAGV),
HOCKY TINYINT,
NAM SMALLINT,
TUNGAY SMALLDATETIME,
DENNGAY SMALLDATETIME,
CONSTRAINT KQGIANGDAY PRIMARY KEY(MALOP,MAMH)
)
CREATE TABLE KETQUATHI
(
MAHV CHAR(5) FOREIGN KEY REFERENCES HOCVIEN(MAHV),
MAMH VARCHAR(10) FOREIGN KEY REFERENCES MONHOC(MAMH),
LANTHI TINYINT,
NGTHI SMALLDATETIME,
DIEM NUMERIC(4,2),
KQUA VARCHAR(10),
CONSTRAINT KQT PRIMARY KEY(MAHV,MAMH,LANTHI)
)

ALTER TABLE HOCVIEN ADD GHICHU VARCHAR(50);
ALTER TABLE HOCVIEN ADD DIEMTB TINYINT;
ALTER TABLE HOCVIEN ADD XEPLOAI CHAR(10);

CREATE TRIGGER MA_HOC_VIEN
ON HOCVIEN
FOR INSERT, UPDATE 
AS
BEGIN
	DECLARE @SISO INT, @MAHV VARCHAR(5), @MALOP VARCHAR(3)
    SELECT @MAHV = MAHV, @MALOP = MALOP FROM INSERTED
	SELECT @SISO = SISO FROM LOP WHERE LOP.MALOP = @MALOP
    IF LEFT(@MAHV,3) <> @MALOP
	BEGIN
		PRINT('3 ki tu dau cua MAHV phai la MALOP')
		ROLLBACK TRANSACTION
	END
	
	ELSE IF CAST(RIGHT(@MAHV, 2) AS INT) NOT BETWEEN 1 AND @SISO
	BEGIN
		PRINT('2 ki tu cuoi cua MAHV phai la so thu tu hoc vien trong lop')
		ROLLBACK TRANSACTION
	END
END

ALTER TABLE HOCVIEN ADD CONSTRAINT GIOI_TINH CHECK (GIOITINH IN('NAM','NU'));
ALTER TABLE KETQUATHI ADD CONSTRAINT CHECK_DIEM CHECK 
(
	DIEM BETWEEN 0 AND 10
	AND RIGHT(CAST(DIEM AS VARCHAR), 3) LIKE '.__'
)
ALTER TABLE KETQUATHI ADD CONSTRAINT CHECK_KQHT CHECK 
(
(KQUA='KHONG DAT' AND DIEM < 5 )OR(KQUA='DAT' AND DIEM BETWEEN 5 AND 10)
)
ALTER TABLE KETQUATHI ADD CONSTRAINT LAN_THI CHECK (LANTHI <=3);
ALTER TABLE GIANGDAY ADD CONSTRAINT CHECK_HK CHECK (HOCKY BETWEEN 1 AND 3);
ALTER TABLE GIAOVIEN ADD CONSTRAINT HOC_VI CHECK (HOCVI IN('CN','KS','Ths','TS','PTS'));

ALTER TABLE LOP ADD	CONSTRAINT FK_MAGVCN FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV)
ALTER TABLE HOCVIEN ADD CONSTRAINT FK_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
ALTER TABLE GIAOVIEN ADD CONSTRAINT FK_MAKHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
ALTER TABLE DIEUKIEN ADD CONSTRAINT FK_MAMH_TRUOC FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH)

-- TUAN 2

-- I.9
CREATE TRIGGER trg_ins_udt_LopTruong ON LOP
FOR INSERT, UPDATE
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM INSERTED I, HOCVIEN HV
	WHERE I.TRGLOP = HV.MAHV AND I.MALOP = HV.MALOP)
	BEGIN
		PRINT 'Error: Lop truong cua mot lop phai la hoc vien cua lop do'
		ROLLBACK TRANSACTION
	END
END
--I.11
ALTER TABLE HOCVIEN ADD CONSTRAINT CHECK_TUOI CHECK (YEAR(GETDATE()) - YEAR(NGSINH) >= 18)

ALTER TABLE GIANGDAY ADD CONSTRAINT CHECK_NGAY_DAY CHECK(TUNGAY < DENNGAY)

ALTER TABLE GIAOVIEN ADD CONSTRAINT CHECK_TUOI_GV CHECK(YEAR(NGVL) - YEAR(NGSINH) >= 22)

ALTER TABLE MONHOC ADD CONSTRAINT CHECK_MON CHECK(ABS(TCLT-TCTH)<=3)