CREATE DATABASE QLMB
USE QLMB
-- CAU 1
CREATE TABLE CHUYENBAY(
    MaCB	char(5) PRIMARY KEY,
	NoiXP	char(15),
	NoiDEN	char(15),
	MaPhiCo	char(5),
	TienCongCB	money
)
CREATE TABLE PHICO 
(
 MAPHICO CHAR(5) PRIMARY KEY,
 TENPHICO CHAR(25),
 KCBAY INT
)
CREATE TABLE PHICONG
(
  MAPHICONG CHAR(5) PRIMARY KEY,
  TENPHICONG CHAR(25),
  LUONG MONEY,
  SOLUONGCB INT
)
CREATE TABLE LICHBAY
(
 MAPHICONG CHAR(5) FOREIGN KEY REFERENCES PHICONG(MAPHICONG),
 MACB CHAR(5) FOREIGN KEY REFERENCES CHUYENBAY(MACB),
 CONSTRAINT PK_LICHBAY PRIMARY KEY (MAPHICONG,MACB),
 NGAYBAY SMALLDATETIME
)
ALTER TABLE CHUYENBAY ADD CONSTRAINT FK_MAPHICO FOREIGN KEY (MAPHICO)  REFERENCES PHICO(MAPHICO)
-- TAO BANG TUY` CHON.
-- CAU 2
-- 2.1
ALTER TABLE PHICO ADD CONSTRAINT CHECK_PHICO CHECK(TENPHICO IN ('Airbus', 'Boeing','Airspeed','BAC'))
-- 2.2
ALTER TABLE CHUYENBAY ADD CONSTRAINT CHECK_CB CHECK (NoiXP <> NoiDEN)
-- 2.3
CREATE TRIGGER PHICONG_CB ON CHUYENBAY FOR INSERT,UPDATE
AS 
BEGIN
    DECLARE @MACB CHAR(5)
    SELECT @MACB = MACB FROM inserted
    IF(EXISTS(SELECT * FROM LICHBAY LBX, INSERTED WHERE LBX.MACB = @MACB AND EXISTS (SELECT * FROM PHICONG WHERE LBX.MAPHICONG = PHICONG.MAPHICONG AND SOLUONGCB > 100)))
        
            UPDATE CHUYENBAY SET TIENCONGCB = 10000000 WHERE CHUYENBAY.MaCB = @MACB
        
END
-- CAU 3
-- 3.1
SELECT MACB
FROM CHUYENBAY
WHERE NOIDEN = 'HANOI' 
UNION
SELECT MACB
FROM CHUYENBAY
WHERE NOIDEN = 'HCM'
--3.2
SELECT TENPHICO, TENPHICONG
FROM PHICO, PHICONG
GROUP BY MAPHICO
HAVING SUM (KCBAY) >= ALL(SELECT SUM(KCBAY) FROM PHICO GROUP BY MAPHICO)
-- 3.3 C
SELECT YEAR(NGAYBAY),NoiDEN FROM LICHBAY LBX, CHUYENBAY WHERE LBX.MACB = CHUYENBAY.MaCB AND EXISTS (
    SELECT SOLUONGCB FROM PHICONG GROUP BY SOLUONGCB HAVING PHICONG.MAPHICONG = LBX.MAPHICONG AND SOLUONGCB = MAX(SOLUONGCB)
)
-- 3.4
SELECT MAPHICONG,TENPHICONG FROM PHICONG WHERE LUONG > 100000000 ORDER BY SOLUONGCB DESC
-- 3.5
SELECT NGAYBAY FROM LICHBAY, PHICONG WHERE LICHBAY.MAPHICONG = PHICONG.MAPHICONG
    GROUP BY NGAYBAY HAVING COUNT(PHICONG.MAPHICONG) >= COUNT(LICHBAY.MACB)
